/*
 * This file is generated by jOOQ.
 */
package com.home.jooq.entity;


import com.home.jooq.entity.tables.Article;
import com.home.jooq.entity.tables.Author;


/**
 * Convenience access to all tables in testing
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testing.ARTICLE</code>.
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>testing.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
